vm:
    name: mesos-121
    group: /mesos
    net:
        vboxnet0: 192.168.56.121
        vboxnet1: 192.168.57.121

    # add route
    route:
        192.168.1.0/24: 192.168.56.1
        192.168.3.0/24: 192.168.56.1

    # specs
    cpu: 2
    mem: 2048

    box: bento/ubuntu-18.04

    # folder shared by host to vm
    shared_host_src: /mnt/sda/vms/shared
    shared_vm_dst: /shared
